### ISSUE TITLE
Did not manage to make this work on my machine....

### ISSUE THREAD

**Issue by pascalfleury** [anticodeninja/michel2#1]
Not a very specific issue, but I did not get this to work at all, even after having read and fixed some code.

Things I needed to do so that it at least starts:
- this only works with python3. Ubuntu 18.04 still ships with python2 as the default, so installing libs with `pip` or `easy_install` will make them go to the wrong place.
- the '-h' options is lying. The commands have no dashes, and you need both an orgfile _and_ a url parameter. From reading the code, I figured you need something like 'gtask://<profile>/<listname>' even though the profile is currently ignored. Also, you _must_ provide a path with both, or it fails.
- you need oauth2client as a dep as well (fails very late in the process)

After all that, I managed to get it to start, and went through the auth process, which worked. Now, I cannot sync any list, as it complains about a text without a task. I did not dig deeper here though:

```
$ michel sync google_tasks.org gtask://fleury/TheList
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/michel2-0.8.0-py3.6.egg/michel/tasktree.py", line 310, in parse_text
    indent_level = len(matches[0][0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/michel", line 11, in <module>
    load_entry_point('michel2==0.8.0', 'console_scripts', 'michel')()
  File "/usr/local/lib/python3.6/dist-packages/michel2-0.8.0-py3.6.egg/michel/__init__.py", line 157, in main
    sync_todolist(args.orgfile, args.url, args.only_todo)
  File "/usr/local/lib/python3.6/dist-packages/michel2-0.8.0-py3.6.egg/michel/__init__.py", line 81, in sync_todolist
    base_tree = TasksTree.parse_file(base_path) if os.path.exists(base_path) else None
  File "/usr/local/lib/python3.6/dist-packages/michel2-0.8.0-py3.6.egg/michel/tasktree.py", line 293, in parse_file
    return TasksTree.parse_text(file_text)
  File "/usr/local/lib/python3.6/dist-packages/michel2-0.8.0-py3.6.egg/michel/tasktree.py", line 329, in parse_text
    raise ValueError("Text without task is not permitted")
ValueError: Text without task is not permitted

```

Also questions for which I have no answer yet are: 
 - can I sync all the task lists into a single file with sections ?
 - how to specify the default list ? (@default did not seem to work, maybe due to another problem as mentioned above)
 - I have a list with non-ascii chars (e.g. 'à faire') how is this represented in the 'url' ? 

What I would do is to sync all to-do lists in the same file, with an additional level of structure (the power of org-mode). And also then just leave the whole url away, so the user only has to specify a token that she wants to sync with 'the Google' and let the script deal with the rest of the stuff.

**Comment by anticodeninja** [comment]
Hello @pascalfleury, thanks for your feedback!
1. I will update repo help and setup.py to make installation process smoother in the nearest future.
2. I know the root cause for "ValueError: Text without task is not permitted", I do not use this functionality of emacs org-mode actively, but anyway I plan to support it and I think this issue is a good reason to do it now.
3. After it, I can help/fix your other problems, but if you provide minimal samples of org-mode files which lead to these problems it will be very helpful.

**Comment by anticodeninja** [comment]
Hi @pascalfleury!
I have fixed ValueError, incorrect handling a tasklist name with a space character and other small issues, such command as `michel push test.org "gtask://__default/à faire"` should work now. Could you check it and describe other issues more precisely?

**Comment by pascalfleury** [comment]
Ok, the tool now installs smoothly and I could sync my tasks with a file, indeed even with some UTF-8 thrown in.

I updated the doc, you should see it in pull-request #2 

I will close this unspecific bug, and will likely open new more specific ones when I find issues.
